kinde-oss/kinde-translations

en/auth.json

- Added `receiver_domain` and replaced a duplicated instance of `business_name`.

add receiver_domain variable

---

pt-BR/auth.json

- Added Brazilian Portuguese translation. `(pt-BR)`

add brazilian portuguese translation

---

auth-schema.json

Schema for the auth json files

Auth flows json schema

---

README.md

Steps for contributing a language 

Guide for how to contribute a language

---

ru/auth.json

Russian translation - updated to latest spec

---

ru/auth.json

Some phrases were not natural in Russian, and there were mistakes in some words. This PR corrects it for the Russian translation.
_Suppose there is a related issue with enough detail for a reviewer to understand your changes fully. In that case, you can omit an explanation and instead include either “Fixes #XX” or “Updates #XX” where “XX” is the issue number._

fix: some phrases for ru translation

---

auth-schema.json
en-GB/auth.json
en-US/auth.json
en/auth.json

Some general error messages were missing translations

feat: add general error messages

---

tr/auth.json

Add TR translations for disclaimer and its variates

---

auth-schema.json
en-AU/auth.json
en-GB/auth.json
en-US/auth.json
en/auth.json

Account not found page was not previoulsy using translations

Add "Account not found" page English

---

auth-schema.json
en-AU/auth.json
en-GB/auth.json
en-US/auth.json
en/auth.json

Add English translations for Phone auth screens

feat: add translations for phone auth

---

cs/auth.json

_Suppose there is a related issue with enough detail for a reviewer to understand your changes fully. In that case, you can omit an explanation and instead include either “Fixes #XX” or “Updates #XX” where “XX” is the issue number._

feat: add czech translations for phone auth

---

README.md
fil/auth.json

Hi @evgenyk and @DaveOrDead,
I've made some updates to the Readme.md file and added some translated files in fil (`fil/auth.json`). 
Feel free to provide any feedback. I felt it was necessary to enhance the user experience for contributors and prevent potential misuse of language contributions. By requesting translators to briefly explain their experiences with translations, we aim to add credibility to the contributions. 
Thank you!
PS ** I notice Dave added more schema structure, im deciding whether adding a live progress bar on readme file for each translated language(e.g. sv/auth.json) 
**
Checklist
✅I have read the [“Pull requests” section](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md#pull-requests) in the [contributing …

Improved ReadMe.md and added fil  phone_number_component

---

es/auth.json

Added Spanish translations for general_errors, account_not_found_page, phone_number_component and mfa_email_page

Added new Spanish translations

---

auth-schema.json
en-AU/auth.json
en-GB/auth.json
en-US/auth.json
en/auth.json
package-lock.json

Add username EN versions and other missing translations

Udate en based translations to include username and error msgs

---

en-AU/auth.json
en-GB/auth.json
en-US/auth.json
en/auth.json

_Suppose there is a related issue with enough detail for a reviewer to understand your changes fully. In that case, you can omit an explanation and instead include either “Fixes #XX” or “Updates #XX” where “XX” is the issue number._

typo: update to `username or email`

---

pt-BR/auth.json

Added missing `pt-BR` translations.

Added missing `pt-BR` translations

---

vi/auth.json

- **Smooth Vietnamese:** Updated Vietnamese translations for natural and accurate phrasing.
- **OTP Consistency:**  Replaced occurrences of "Mã một lần" with "OTP" to align with common Vietnamese usage.
- **Translation Updates:** Added Vietnamese translations for "username" and additional validation messages to ensure a fully localized experience.

Improve Vietnamese Localization

---

auth-schema.json
en-AU/auth.json
en-GB/auth.json
en-US/auth.json
en/auth.json

Add keys for marketing checkbox

feat: add marketing widget key

---

auth-schema.json
en-AU/auth.json
en-GB/auth.json
en-US/auth.json
en/auth.json

Update property key to be more descriptive

---

.github/workflows/validation.yml

Update the Python package (`jsonschema`) installation method according to the GitHub action logs.
Related issue: #97

fix(actions): update python package installation for action

---

pt-BR/auth.json

Add new keys to the Brazilian portuguese translation file.

chore: add new keys to pt-BR

---

fr/auth.json

Updating French email translations

Update french email translations

---

ar-001/auth.json

Create account screen is displaying english text as the arabic translation file is not covering all pages and labels.
I've added the missing required sections and the validation check is green now for arabic language.
Backgorund : I'm an arabic native speaker and i run this arabic project : https://www.alcryptocast.com/ that uses Kinde

Update standard arabic translations

---

it/auth.json

Updated the Italian translation of "underscore".
Related comment here: https://github.com/kinde-oss/kinde-translations/pull/94/files#r1796377721

Update 'underscore' translation in Italian (it) translation

---

ar-001/auth.json
auth-schema.json
cs/auth.json
da/auth.json
de/auth.json
en-AU/auth.json
en-GB/auth.json
en-US/auth.json
en/auth.json
es/auth.json
fa/auth.json
fil/auth.json
fr/auth.json
hu/auth.json
it/auth.json
ja/auth.json
ko/auth.json
lv/auth.json
mn/auth.json
nl-BE/auth.json
nl/auth.json
no/auth.json
pt-BR/auth.json
sr/auth.json
th/auth.json
tr/auth.json
vi/auth.json
zh-Hans/auth.json
zh-Hant/auth.json

Add choose method link translation for email MFA

MFA Email - add choose method link

---

auth-schema.json
en/auth.json

Link expired messages

---

en/auth.json

Add org auth connection error message

Add error message

---

auth-schema.json
en-AU/auth.json
en-GB/auth.json
en-US/auth.json
en/auth.json

Adds English translation files for billing pages in the auth flow

Add billing page defaults

---

fr/auth.json

Updated incorrect translations

Update french auth.json

---

.github/workflows/seed.yml
.gitignore
en/auth.json
json-diff-checker.ts
package-lock.json
package.json
sync-and-translate.ts

To improve the overall quality of the translation files, when new translation keys are added, they are automatically translated and pushed to the repo when a PR is raised. 
This will use the `en/auth.json` as the main driving key

Add translation seed workflow

---

en/auth.json

_Suppose there is a related issue with enough detail for a reviewer to understand your changes fully. In that case, you can omit an explanation and instead include either “Fixes #XX” or “Updates #XX” where “XX” is the issue number._

en Auth Translation Dictionary, translate_context added
